version: '3'

tasks:
  start-postgres:
    desc: Start a Postgres server via docker compose
    cmds:
      - docker compose up -d

  stop-postgres:
    desc: Stops Postgres server via docker compose
    cmds:
      - docker compose down

  migrate-up:
    desc: Sets up the database to run Snippetbox as a web app
    cmds:
      - go run ./cmd/migration up

  migrate-down:
    desc: Deletes the database used by Snippetbox
    cmds:
      - go run ./cmd/migration down

  generate-tls-cert:
    dir: ./tls
    desc: Generates TLS certificate to run Snippetbox on HTTPS
    cmds:
      - go run {{.GOROOT}}/src/crypto/tls/generate_cert.go --rsa-bits=2048 --host=localhost

  run:
    desc: Runs Snippetbox as a web application
    cmds:
      - go run ./cmd/web

  tests:
    desc: Runs only unit tests
    cmds:
      - go test -json -v --coverprofile=coverage.out ./... 2>&1 | gotestfmt -hide "successful-tests, empty-packages"

  all-tests:
    desc: Runs all tests
    env:
      INTEGRATION: true
    cmds:
      - go test -json -v --coverprofile=coverage.out ./... 2>&1 | gotestfmt -hide "successful-tests, empty-packages"
