version: '3'

dotenv: ['.env']

tasks:
  init-db:
    cmds:
      - psql -U postgres -c "CREATE DATABASE {{.DB_NAME}};"
      - psql -U postgres -c "CREATE USER {{.DB_USER}} WITH PASSWORD '{{.DB_PASSWORD}}';"
      - psql -U postgres -d {{.DB_NAME}} -f ./migration/setup.sql
      - psql -U postgres -d {{.DB_NAME}} -c "GRANT SELECT, INSERT, UPDATE, DELETE ON snippets, sessions, users TO {{.DB_USER}};"

  drop-db:
    cmds:
      - psql -U postgres -c "DROP DATABASE IF EXISTS {{.DB_NAME}};"
      - psql -U postgres -c "DROP USER IF EXISTS {{.DB_USER}};"

  run:
    desc: Runs the main package
    cmds:
      - go run ./cmd/web

  test:
    desc: Runs all tests
    cmds:
      - go test ./... {{.CLI_ARGS}}
