version: '3'

dotenv: ['.env']

tasks:
  migrate-up:
    cmds:
      - go run ./cmd/migration up

  migrate-down:
    cmds:
      - go run ./cmd/migration down

  run:
    desc: Runs Snippetbox as a web application
    cmds:
      - go run ./cmd/web

  test:
    desc: Runs all tests
    cmds:
      - go test ./... {{.CLI_ARGS}}
