name: Run All Tests

on: [ push, pull_request ]

jobs:
  all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'

      - name: Install Dependencies
        run: go get ./...

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b $HOME/bin
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2

      - name: Run All Tests
        run: task test -- -json -v 2>&1 | gotestfmt


    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
